# distributed training
nodes: 1
gpus: 1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 24
dataset_dir: "./datasets"

# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 256
image_size: 224
n_classes: 50
n_img_class: 1000
n_img_samples_per_class: 10 # Number of negative images generated per class.
num_variations: 10
transform_type: 0 # 0: SimCLR, 1: ImageVariation, 2: SimCLR or ImageVariation (randomly chosen) 3: ImageVariation + SimCLR
start_epoch: 0
epochs: 100
dataset: "Demon-Imagenet" # "HS-Imagenet" or "Imagenet-1pct" or "Imagenet-10pct" or "Imagenette" or "Demon-Imagenet" or "Almighty-Imagenet"
pretrain: True
include_neg_samples: False
neg_train_steps: True
ns_batch_size: 512 # number of negative samples per batch

# model options
resnet: "resnet50"
projection_dim: 64 # "[...] to project the representation to a 128-dimensional latent space"

# loss options
optimizer: "Adam" # or LARS (experimental)
weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10−6"
temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes

# reload options
model_path: "final-demon-transform0-save-batch256-resnet50" # set to the directory containing `checkpoint_##.tar` 
epoch_num: 100 # set to checkpoint number
reload: False

# logistic regression options
logistic_batch_size: 256
logistic_epochs: 500
